"""Holly Seed-1: original implementation of a small neural character model.
Standard embedding/MLP mathematics; no claim of a new research architecture.
Only NumPy array arithmetic is used. No framework or pretrained parameters.
"""
import argparse
import hashlib
import json
import os
import tempfile
from pathlib import Path
import numpy as np

CTX, EMB, HID, VOCAB, SCALE = 64, 8, 64, 98, 4096
SHAPES = {'embedding': (VOCAB, EMB), 'hidden': (CTX*EMB, HID),
          'hidden_bias': (HID,), 'output': (HID, VOCAB), 'output_bias': (VOCAB,)}

def encode(text):
    if any(c != '\n' and not ' ' <= c <= '~' for c in text):
        raise ValueError('Seed-1 accepts printable ASCII and newline only')
    return [2 if c == '\n' else ord(c)-29 for c in text]

def decode(tokens):
    return ''.join('\n' if t == 2 else chr(t+29) for t in tokens if t >= 2)

def examples(path):
    records = [s.strip() for s in Path(path).read_text(encoding='utf-8').split('\n\n') if s.strip()]
    if not records:
        raise ValueError('Corpus has no records')
    xs, ys = [], []
    for record in records:
        context = [0]*CTX
        for token in encode(record)+[1]:
            xs.append(context.copy()); ys.append(token)
            context = context[1:]+[token]
    return records, np.array(xs, dtype=np.int64), np.array(ys, dtype=np.int64)

def initialize(seed=42):
    rng = np.random.default_rng(seed)
    return {k: (np.zeros(s) if 'bias' in k else rng.normal(0, .08 if k == 'embedding' else 1/np.sqrt(s[0]), s))
            for k,s in SHAPES.items()}

def loss_grad(p, x, y, gradients=True):
    e = p['embedding'][x].reshape(len(x), -1)
    z = e @ p['hidden'] + p['hidden_bias']
    h = np.clip(z, -1, 1)
    logits = h @ p['output'] + p['output_bias']
    logits -= logits.max(axis=1, keepdims=True)
    prob = np.exp(logits); prob /= prob.sum(axis=1, keepdims=True)
    loss = -np.log(np.maximum(prob[np.arange(len(y)), y], 1e-300)).mean()
    if not gradients:
        return float(loss)
    d = prob.copy(); d[np.arange(len(y)), y] -= 1; d /= len(y)
    dz = (d @ p['output'].T) * (np.abs(z) < 1)
    de = (dz @ p['hidden'].T).reshape(len(x), CTX, EMB)
    g = {'output': h.T @ d, 'output_bias': d.sum(axis=0),
         'hidden': e.T @ dz, 'hidden_bias': dz.sum(axis=0),
         'embedding': np.zeros_like(p['embedding'])}
    np.add.at(g['embedding'], x, de)
    return float(loss), g

def evaluate(p, x, y):
    return sum(loss_grad(p,x[i:i+256],y[i:i+256],False)*len(y[i:i+256])
               for i in range(0,len(y),256))/len(y)

def quantize(p):
    return {k: np.rint(v*SCALE).clip(-32768,32767).astype(np.int16) for k,v in p.items()}

def trunc_div(v):
    return np.where(v >= 0, v//SCALE, -((-v)//SCALE))

def fixed_logits(q, context):
    e = q['embedding'][context].reshape(-1).astype(np.int64)
    h = np.clip(trunc_div(e @ q['hidden'].astype(np.int64))+q['hidden_bias'], -SCALE, SCALE)
    return trunc_div(h @ q['output'].astype(np.int64))+q['output_bias']

def generate(q, prompt, limit=96):
    context = ([0]*CTX+encode(prompt))[-CTX:]
    result = []
    for _ in range(limit):
        logits = fixed_logits(q,context)
        token = int(np.argmax(logits[1:]))+1
        if token == 1: break
        result.append(token); context = context[1:]+[token]
    return decode(result)

def load(path):
    with np.load(path,allow_pickle=False) as z:
        p = {k: z[k].copy() for k in SHAPES}
    for k,s in SHAPES.items():
        if p[k].shape != s or not np.isfinite(p[k]).all() or np.max(np.abs(p[k])) > 7.99:
            raise ValueError('Invalid checkpoint: '+k)
    return p

def export(p, path):
    q = quantize(p)
    lines = ['/* Generated by model/holly_lm.py; original Seed-1 demonstration weights. */',
             '#ifndef HOLLY_LM_WEIGHTS_H', '#define HOLLY_LM_WEIGHTS_H']
    for k,v in q.items():
        lines.append('static const int16_t lm_'+k+'['+str(v.size)+'] = {')
        a = v.ravel()
        lines.extend(','.join(map(str,a[i:i+24]))+',' for i in range(0,len(a),24))
        lines.append('};')
    lines.append('#endif')
    Path(path).write_text('\n'.join(lines)+'\n')

def adam_step(p, m, v, rng, x, y, step):
    idx=rng.integers(len(y),size=64)
    loss,g=loss_grad(p,x[idx],y[idx])
    norm=np.sqrt(sum(np.sum(a*a) for a in g.values()))
    for k in p:
        g[k] *= min(1,1/max(norm,1e-12))
        m[k]=.9*m[k]+.1*g[k]; v[k]=.999*v[k]+.001*g[k]*g[k]
        p[k] -= .002*(m[k]/(1-.9**step))/(np.sqrt(v[k]/(1-.999**step))+1e-8)
        np.clip(p[k],-7.99,7.99,out=p[k])
    return loss

def save_training(path,p,m,v,best_p,step,best_step,rng,train_hash,valid_hash):
    # Atomic replacement keeps the last complete host checkpoint on interruption.
    data=dict(best_p)
    for prefix,values in [('current_',p),('adam_m_',m),('adam_v_',v)]:
        data.update({prefix+k:a for k,a in values.items()})
    metadata={'version':1,'step':step,'best_step':best_step,'rng':rng.bit_generator.state,
              'train_sha256':train_hash,'valid_sha256':valid_hash}
    data['training_metadata']=np.frombuffer(json.dumps(metadata).encode(),dtype=np.uint8)
    path=Path(path);path.parent.mkdir(parents=True,exist_ok=True)
    fd,tmp=tempfile.mkstemp(dir=path.parent,prefix=path.name+'.',suffix='.tmp')
    try:
        with os.fdopen(fd,'wb') as f:
            np.savez(f,**data);f.flush();os.fsync(f.fileno())
        os.replace(tmp,path)
    finally:
        if os.path.exists(tmp):os.unlink(tmp)

def restore_training(path):
    best=load(path)
    with np.load(path,allow_pickle=False) as z:
        meta=json.loads(z['training_metadata'].tobytes())
        values=[]
        for prefix in ['current_','adam_m_','adam_v_']:
            group={k:z[prefix+k].copy() for k in SHAPES}
            for k,shape in SHAPES.items():
                if group[k].shape!=shape or not np.isfinite(group[k]).all():raise ValueError('Invalid optimizer array')
                if prefix=='current_' and np.max(np.abs(group[k]))>7.99:raise ValueError('Parameter range')
                if prefix=='adam_v_' and np.min(group[k])<0:raise ValueError('Negative optimizer variance')
            values.append(group)
    if meta['version']!=1 or not 0<=meta['best_step']<=meta['step']<2**31:raise ValueError('Invalid training state')
    rng=np.random.default_rng();rng.bit_generator.state=meta['rng']
    return (*values,best,meta,rng)

def train(args):
    if Path(args.output).suffix!='.npz':raise ValueError('Output must end with .npz')
    records,x,y=examples(args.train); valid,vx,vy=examples(args.valid)
    if set(records)&set(valid):raise ValueError('Train/validation records overlap')
    if args.steps<1:raise ValueError('steps must be positive')
    train_hash=hashlib.sha256(Path(args.train).read_bytes()).hexdigest()
    valid_hash=hashlib.sha256(Path(args.valid).read_bytes()).hexdigest()
    if args.resume:
        p,m,v,best_p,meta,rng=restore_training(args.resume)
        changed=(train_hash!=meta['train_sha256'] or valid_hash!=meta['valid_sha256'])
        if changed and not args.allow_data_change:raise ValueError('Dataset changed: retain replay data and explicitly use --allow-data-change')
        start=meta['step'];best_step=meta['best_step']
        if changed:best_p={k:a.copy() for k,a in p.items()};best_step=start
    else:
        p=load(args.warm_start) if args.warm_start else initialize(args.seed)
        rng=np.random.default_rng(args.seed+1);m={k:np.zeros_like(a) for k,a in p.items()};v={k:a.copy() for k,a in m.items()}
        start=best_step=0;best_p={k:a.copy() for k,a in p.items()}
    initial=evaluate(p,vx,vy);best=evaluate(best_p,vx,vy);history=[]
    for step in range(start+1,start+args.steps+1):
        loss=adam_step(p,m,v,rng,x,y,step)
        if step%250==0 or step==start+args.steps:
            score=evaluate(p,vx,vy);entry={'step':step,'train_batch_loss':loss,'validation_loss':score}
            history.append(entry);print(json.dumps(entry),flush=True)
            if score<best:best=score;best_step=step;best_p={k:a.copy() for k,a in p.items()}
            save_training(args.output,p,m,v,best_p,step,best_step,rng,train_hash,valid_hash)
    report={'model':'Holly Seed-1','parameters':sum(a.size for a in p.values()),'seed':args.seed,
            'context_characters':CTX,'initial_validation_loss':initial,'best_validation_loss':best,
            'best_step':best_step,'start_step':start,'steps':args.steps,'train_records':len(records),
            'validation_records':len(valid),'train_sha256':train_hash,'valid_sha256':valid_hash,
            'history':history,'scope':'Validation selects exported weights; current weights, optimizer and RNG are saved separately for exact resume.'}
    Path(str(args.output)+'.json').write_text(json.dumps(report,indent=2)+'\n')
    if args.header:export(best_p,args.header)
    print(json.dumps({k:v for k,v in report.items() if k!='history'},indent=2))

if __name__=='__main__':
    parser=argparse.ArgumentParser(description=__doc__)
    sub=parser.add_subparsers(dest='command',required=True)
    t=sub.add_parser('train'); t.add_argument('--train',required=True); t.add_argument('--valid',required=True)
    t.add_argument('--steps',type=int,default=4000); t.add_argument('--seed',type=int,default=42)
    t.add_argument('--output',required=True); t.add_argument('--header')
    source=t.add_mutually_exclusive_group();source.add_argument('--resume');source.add_argument('--warm-start')
    t.add_argument('--allow-data-change',action='store_true')
    e=sub.add_parser('export'); e.add_argument('checkpoint'); e.add_argument('header')
    g=sub.add_parser('generate'); g.add_argument('checkpoint'); g.add_argument('prompt')
    args=parser.parse_args()
    if args.command=='train': train(args)
    elif args.command=='export': export(load(args.checkpoint),args.header)
    else: print(generate(quantize(load(args.checkpoint)),args.prompt))
