#include <assert.h>
#include <stdio.h>
#include <string.h>
#include "holly.h"
static char result[1024];static unsigned used;
static char saved_inputs[8][320],saved_outputs[8][640];static unsigned saved_count;
static struct holly_memory_item stored_memory[4];static unsigned stored_memory_count;
static void capture(const char *s,void *context) {
 (void)context;while(*s&&used+1<sizeof(result))result[used++]=*s++;result[used]=0;
}
static void run(char *line) {used=0;result[0]=0;assert(holly_command(line,capture,0)==0);}
static int save_turn(const char *input,const char *output,void *context) {
 (void)context;if(saved_count==8)return -1;
 snprintf(saved_inputs[saved_count],sizeof(saved_inputs[0]),"%s",input);
 snprintf(saved_outputs[saved_count],sizeof(saved_outputs[0]),"%s",output);
 saved_count++;return 0;
}
static int get_turn(unsigned back,char *input,unsigned input_cap,char *output,unsigned output_cap,void *context) {
 (void)context;if(back>=saved_count)return -1;unsigned at=saved_count-1u-back;
 if(strlen(saved_inputs[at])+1>input_cap||strlen(saved_outputs[at])+1>output_cap)return -1;
 strcpy(input,saved_inputs[at]);strcpy(output,saved_outputs[at]);return 0;
}
static unsigned count_turns(void *context) {(void)context;return saved_count;}
static int memory_add(const char *text,const char *source,unsigned confidence,uint32_t *id,void *context) {
 (void)context;if(stored_memory_count==4)return -1;
 struct holly_memory_item *item=&stored_memory[stored_memory_count];memset(item,0,sizeof(*item));
 item->id=++stored_memory_count;item->revision=1;item->confidence=confidence;
 snprintf(item->text,sizeof(item->text),"%s",text);snprintf(item->source,sizeof(item->source),"%s",source);
 *id=item->id;return 0;
}
static unsigned memory_count(void *context) {(void)context;return stored_memory_count;}
static int memory_get(uint32_t id,struct holly_memory_item *out,void *context) {
 (void)context;if(!id||id>4||!stored_memory[id-1].id)return -1;*out=stored_memory[id-1];return 0;
}
static int memory_get_at(unsigned index,struct holly_memory_item *out,void *context) {
 (void)context;for(unsigned i=0;i<4;i++)if(stored_memory[i].id){if(!index--){*out=stored_memory[i];return 0;}}
 return -1;
}
static int memory_update(uint32_t id,const char *text,const char *source,unsigned confidence,void *context) {
 (void)context;struct holly_memory_item *item=id&&id<=4?&stored_memory[id-1]:0;
 if(!item||!item->id)return -1;
 snprintf(item->text,sizeof(item->text),"%s",text);
 snprintf(item->source,sizeof(item->source),"%s",source);item->confidence=confidence;item->revision++;return 0;
}
static int memory_forget(uint32_t id,void *context) {
 (void)context;if(!id||id>4||!stored_memory[id-1].id)return -1;
 memset(&stored_memory[id-1],0,sizeof(stored_memory[0]));stored_memory_count--;return 0;
}
int main(void) {
 char unknown[]="ask What is Holly?";run(unknown);assert(strstr(result,"more detail"));
 char lesson[]="teach What is Holly? => A ship computer.";run(lesson);assert(strstr(result,"in memory"));
 char ask[]="ask What is Holly?";run(ask);assert(strstr(result,"A ship computer."));
 char status[]="status";run(status);assert(strstr(result,"lessons reset on reboot"));
 struct holly_session voice,ssh;
 holly_session_init(&voice);holly_session_init(&ssh);
 used=0;result[0]=0;
 assert(holly_turn(&voice,"  hello  ",capture,0)==0);
 assert(strstr(result,"Hello") && voice.turns==1 && voice.expression==HOLLY_SPEAKING);
 used=0;result[0]=0;
 assert(holly_turn(&voice,"What is Holly?",capture,0)==0);
 assert(strstr(result,"A ship computer.") && voice.turns==2);
 used=0;result[0]=0;
 assert(holly_turn(&voice,"repeat that",capture,0)==0);
 assert(strstr(result,"A ship computer."));
 used=0;result[0]=0;
 assert(holly_turn(&voice,"what were we talking about?",capture,0)==0);
 assert(strstr(result,"What is Holly?"));
 used=0;result[0]=0;
 assert(holly_turn(&ssh,"repeat that",capture,0)==0);
 assert(strstr(result,"haven't answered") && ssh.turns==1);
 used=0;result[0]=0;
 assert(holly_turn(&voice,"unknown obscure subject",capture,0)==0);
 assert(strstr(result,"online reader is unavailable") && voice.expression==HOLLY_THINKING);
 assert(holly_turn(&voice,"",capture,0)==0 && voice.turns==5);
 char long_line[322];memset(long_line,'x',321);long_line[321]=0;
 assert(holly_turn(&voice,long_line,capture,0)==-2 && voice.turns==5);
 holly_set_history(save_turn,get_turn,count_turns,0);saved_count=0;
 holly_session_init(&voice);used=0;result[0]=0;
 assert(holly_turn(&voice,"hello",capture,0)==0&&saved_count==1);
 used=0;result[0]=0;
 assert(holly_turn(&voice,"What is Holly?",capture,0)==0&&saved_count==2);
 used=0;result[0]=0;
 assert(holly_turn(&voice,"history 2",capture,0)==0&&saved_count==2);
 assert(strstr(result,"You: hello")&&strstr(result,"You: What is Holly?")&&strstr(result,"A ship computer."));
 holly_set_history(0,0,0,0);
 static const struct holly_memory_ops memory_api={memory_add,memory_count,memory_get,
     memory_get_at,memory_update,memory_forget};
 holly_set_memory(&memory_api,0);stored_memory_count=0;
 char remember[]="remember Holly was built in 2350 | Captain log | 80";
 run(remember);assert(strstr(result,"Saved memory #1")&&strstr(result,"80%"));
 char find[]="memory find built";run(find);
 assert(strstr(result,"Holly was built in 2350")&&strstr(result,"Captain log"));
 char correct[]="memory correct   1 => Holly was built in 2400.";run(correct);
 assert(strstr(result,"Corrected memory #1"));
 char confidence[]="memory confidence 1 70";run(confidence);
 assert(strstr(result,"now 70%"));
 char show[]="memory show 1";run(show);
 assert(strstr(result,"confidence 70%")&&strstr(result,"user correction")&&strstr(result,"2400"));
 holly_session_init(&voice);used=0;result[0]=0;
 assert(holly_turn(&voice,"When was Holly built?",capture,0)==0);
 assert(strstr(result,"2400")&&strstr(result,"memory #1")&&voice.last_memory_id==1);
 used=0;result[0]=0;
 assert(holly_turn(&voice,"why that?",capture,0)==0);
 assert(strstr(result,"#1 [")&&strstr(result,"user correction"));
 used=0;result[0]=0;
 assert(holly_turn(&voice,"correct that => Holly was built in 2450.",capture,0)==0);
 assert(strstr(result,"Corrected memory #1")&&stored_memory[0].revision==4);
 used=0;result[0]=0;
 assert(holly_turn(&voice,"ask When was Holly built?",capture,0)==0);
 assert(strstr(result,"2450")&&voice.last_memory_id==1);
 char competing[]="remember Holly was built in 2600 | ship archive | 90";
 run(competing);assert(strstr(result,"Saved memory #2"));
 used=0;result[0]=0;
 assert(holly_turn(&voice,"ask When was Holly built?",capture,0)==0);
 assert(strstr(result,"More than one")&&strstr(result,"2450")&&strstr(result,"2600"));
 assert(voice.last_memory_id==0);
 used=0;result[0]=0;
 assert(holly_turn(&voice,"why that?",capture,0)==0);
 assert(strstr(result,"haven't recalled"));
 used=0;result[0]=0;
 assert(holly_turn(&voice,"ask Holly built in 2450",capture,0)==0);
 assert(strstr(result,"2450")&&!strstr(result,"2600")&&voice.last_memory_id==1);
 used=0;result[0]=0;
 assert(holly_turn(&voice,"ask Holly teleporter",capture,0)==0);
 assert(strstr(result,"online reader is unavailable")&&voice.last_memory_id==0);
 char bad_confidence[]="remember invalid | source | 900";run(bad_confidence);
 assert(strstr(result,"confidence(0-100)"));
 char forget[]="memory forget 1";run(forget);
 assert(strstr(result,"Forgotten memory #1")&&memory_count(0)==1);
 char forget_other[]="memory forget 2";run(forget_other);
 assert(strstr(result,"Forgotten memory #2")&&memory_count(0)==0);
 holly_session_init(&voice);assert(voice.learning_enabled==1);
 used=0;result[0]=0;
 assert(holly_turn(&voice,"The ship is Red Dwarf.",capture,0)==0);
 assert(strstr(result,"unverified chat memory #1")&&memory_count(0)==1);
 assert(!strcmp(stored_memory[0].source,"chat statement")&&stored_memory[0].confidence==55);
 used=0;result[0]=0;
 assert(holly_turn(&voice,"the ship is red dwarf",capture,0)==0);
 assert(strstr(result,"already have")&&memory_count(0)==1);
 used=0;result[0]=0;
 assert(holly_turn(&voice,"ask ship Red Dwarf",capture,0)==0);
 assert(strstr(result,"memory #1")&&voice.last_memory_id==1);
 used=0;result[0]=0;
 assert(holly_turn(&voice,"that's right",capture,0)==0);
 assert(stored_memory[0].confidence==75&&stored_memory[0].revision==2);
 used=0;result[0]=0;
 assert(holly_turn(&voice,"that's wrong",capture,0)==0);
 assert(stored_memory[0].confidence==45&&strstr(result,"correct that"));
 used=0;result[0]=0;
 assert(holly_turn(&voice,"correct that => The ship is Blue Dwarf.",capture,0)==0);
 assert(stored_memory[0].confidence==100&&stored_memory[0].revision==4);
 used=0;result[0]=0;
 assert(holly_turn(&voice,"learning off",capture,0)==0&&voice.learning_enabled==0);
 used=0;result[0]=0;
 assert(holly_turn(&voice,"The captain is Dave Lister.",capture,0)==0);
 assert(memory_count(0)==1);
 used=0;result[0]=0;
 assert(holly_turn(&voice,"learning on",capture,0)==0&&voice.learning_enabled==1);
 used=0;result[0]=0;
 assert(holly_turn(&voice,"The captain is Dave Lister.",capture,0)==0);
 assert(strstr(result,"unverified chat memory #2")&&memory_count(0)==2);
 used=0;result[0]=0;
 assert(holly_turn(&voice,"Maybe the captain is Arnold Rimmer.",capture,0)==0);
 assert(memory_count(0)==2);
 used=0;result[0]=0;
 assert(holly_turn(&voice,"The captain is Arnold Rimmer.",capture,0)==0);
 assert(strstr(result,"unverified chat memory #3")&&memory_count(0)==3);
 used=0;result[0]=0;
 assert(holly_turn(&voice,"ask captain",capture,0)==0);
 assert(strstr(result,"More than one")&&voice.last_memory_id==0);
 used=0;result[0]=0;
 assert(holly_turn(&voice,"ask captain Dave",capture,0)==0&&voice.last_memory_id==2);
 assert(holly_turn(&voice,"that's right",capture,0)==0);
 assert(holly_turn(&voice,"that's right",capture,0)==0);
 assert(stored_memory[1].confidence==95);
 used=0;result[0]=0;
 assert(holly_turn(&voice,"ask captain",capture,0)==0);
 assert(strstr(result,"memory #2")&&strstr(result,"Memory #3 also matches")&&voice.last_memory_id==2);
 used=0;result[0]=0;
 assert(holly_turn(&voice,"ask captain Arnold",capture,0)==0&&voice.last_memory_id==3);
 assert(holly_turn(&voice,"that's wrong",capture,0)==0);
 assert(holly_turn(&voice,"that's wrong",capture,0)==0);
 assert(stored_memory[2].confidence==0);
 used=0;result[0]=0;
 assert(holly_turn(&voice,"wiki import Red Dwarf is a television comedy. | https://en.wikipedia.org/wiki/Red_Dwarf",capture,0)==0);
 assert(strstr(result,"Wikipedia excerpt as memory #4")&&stored_memory[3].confidence==45);
 assert(!strcmp(stored_memory[3].source,"https://en.wikipedia.org/wiki/Red_Dwarf"));
 used=0;result[0]=0;
 assert(holly_turn(&voice,"wiki import Red Dwarf is a television comedy. | https://en.wikipedia.org/wiki/Red_Dwarf",capture,0)==0);
 assert(strstr(result,"already memory #4")&&memory_count(0)==4);
 char wrong_source[]="wiki import Red Dwarf is a television comedy. | http://en.wikipedia.org/wiki/Red_Dwarf";
 run(wrong_source);assert(strstr(result,"Use wiki import")&&memory_count(0)==4);
 char wrong_host[]="wiki import Red Dwarf is a television comedy. | https://en.wikipedia.org.evil/wiki/Red_Dwarf";
 run(wrong_host);assert(strstr(result,"Use wiki import")&&memory_count(0)==4);
 used=0;result[0]=0;
 assert(holly_turn(&voice,"ask television comedy",capture,0)==0);
 assert(strstr(result,"Red Dwarf is a television comedy")&&voice.last_memory_id==4);
 used=0;result[0]=0;
 assert(holly_turn(&voice,"why that?",capture,0)==0);
 assert(strstr(result,"https://en.wikipedia.org/wiki/Red_Dwarf"));
 used=0;result[0]=0;
 assert(holly_turn(&voice,"ask captain",capture,0)==0);
 assert(strstr(result,"memory #2")&&!strstr(result,"Memory #3 also matches"));
 holly_session_init(&ssh);assert(ssh.learning_enabled==1);
 holly_set_memory(0,0);
 holly_set_history(0,0,0,0);
 used=0;result[0]=0;
 assert(holly_turn(&ssh,"model status",capture,0)==0);
 assert(strstr(result,"39,986 trained parameters"));
 unsigned before=memory_count(0);
 used=0;result[0]=0;
 assert(holly_turn(&ssh,"model generate Holly is",capture,0)==0);
 assert(strstr(result,"experimental completion")&&memory_count(0)==before);
 used=0;result[0]=0;
 assert(holly_turn(&ssh,"model unknown",capture,0)==0);
 assert(strstr(result,"Use model status"));
 used=0;result[0]=0;
 assert(holly_turn(&ssh,"version",capture,0)==0 && strstr(result,"0.49"));
 used=0;result[0]=0;
 assert(holly_turn(&ssh,"storagediag",capture,0)==0 && strstr(result,"diagnostics unavailable"));
 used=0;result[0]=0;
 assert(holly_turn(&ssh,"displaydiag",capture,0)==0 && strstr(result,"diagnostics unavailable"));
 used=0;result[0]=0;
 assert(holly_turn(&ssh,"chat on",capture,0)==0 && ssh.dialogue_enabled && !ssh.learning_enabled && ssh.dialogue_model==4);
 assert(strstr(result,"1266121 parameters"));
 used=0;result[0]=0;
 assert(holly_turn(&ssh,"how are you",capture,0)==0 && strstr(result,"social life"));
 used=0;result[0]=0;
 assert(holly_turn(&ssh,"personality off",capture,0)==0);
 used=0;result[0]=0;
 assert(holly_turn(&ssh,"how are you",capture,0)==0 && strstr(result,"experimental"));
 assert(ssh.dialogue_previous[0]);
 used=0;result[0]=0;
 assert(holly_turn(&ssh,"chat reset",capture,0)==0 && !ssh.dialogue_previous[0]);
 used=0;result[0]=0;
 assert(holly_turn(&ssh,"chat model 1",capture,0)==0 && ssh.dialogue_model==1);
 assert(strstr(result,"127647 parameters"));
 used=0;result[0]=0;
 assert(holly_turn(&ssh,"chat status",capture,0)==0 && strstr(result,"127647 parameters"));
 used=0;result[0]=0;
 assert(holly_turn(&ssh,"chat model 3",capture,0)==0 && ssh.dialogue_model==3);
 assert(strstr(result,"792193 parameters"));
 used=0;result[0]=0;
 assert(holly_turn(&ssh,"chat off",capture,0)==0 && !ssh.dialogue_enabled);
 holly_session_init(&ssh);assert(!ssh.dialogue_enabled && !ssh.dialogue_previous[0]);
 used=0;result[0]=0;
 assert(holly_turn(&ssh,"dwarf Lister",capture,0)==0&&strstr(result,"stasis"));
 used=0;result[0]=0;
 assert(holly_turn(&ssh,"who plays him",capture,0)==0&&strstr(result,"Craig Charles"));
 used=0;result[0]=0;
 assert(holly_turn(&ssh,"dwarf source",capture,0)==0&&strstr(result,"theend"));
 used=0;result[0]=0;
 assert(holly_turn(&ssh,"tell me a joke",capture,0)==0&&strstr(result,"Holly:"));
 assert(ssh.lore.topic>=0); /* Smalltalk preserves the reference subject. */
 used=0;result[0]=0;
 assert(holly_turn(&ssh,"personality off",capture,0)==0&&!ssh.personality_enabled);
 used=0;result[0]=0;
 assert(holly_turn(&ssh,"dwarf Lister",capture,0)==0&&strstr(result,"stasis"));
 used=0;result[0]=0;
 assert(holly_turn(&ssh,"chat reset",capture,0)==0&&ssh.lore.topic==-1);

 used=0;result[0]=0;
 assert(holly_turn(&ssh,"chat on",capture,0)==0);
 char custom[]="teach how are you => My custom taught reply.";run(custom);
 used=0;result[0]=0;
 assert(holly_turn(&ssh,"how are you",capture,0)==0 && strstr(result,"My custom taught reply") && !strstr(result,"experimental"));
 holly_set_memory(&memory_api,0);memset(stored_memory,0,sizeof(stored_memory));stored_memory_count=0;
 char personal[]="remember My name is Darren and my nickname is Viper.";run(personal);
 used=0;result[0]=0;
 assert(holly_turn(&ssh,"what is my name",capture,0)==0 && strstr(result,"Darren") && ssh.last_memory_id==1);
 char old_context[640];strcpy(old_context,ssh.dialogue_previous);
 used=0;result[0]=0;
 assert(holly_turn(&ssh,"train status",capture,0)==0 && !strcmp(old_context,ssh.dialogue_previous));
 assert(!voice.dialogue_enabled);holly_set_memory(0,0);
 struct holly_session discussion;holly_session_init(&discussion);
 used=0;result[0]=0;
 assert(holly_turn(&discussion,"What do you think about Rimmer?",capture,0)==0);
 assert(strstr(result,"Rimmer")&&strstr(result,"interpretation")&&discussion.discussion_turns==1);
 used=0;result[0]=0;
 assert(holly_turn(&discussion,"I think Rimmer is ridiculous",capture,0)==0);
 assert(strstr(result,"Rimmer")&&strstr(result,"What makes you say")&&discussion.discussion_turns==2);
 used=0;result[0]=0;
 assert(holly_turn(&discussion,"repeat that",capture,0)==0&&strstr(result,"What makes you say"));
 used=0;result[0]=0;
 assert(holly_turn(&discussion,"Why?",capture,0)==0&&strstr(result,"About ")&&strstr(result,"Rimmer"));
 used=0;result[0]=0;
 assert(holly_turn(&discussion,"What if Rimmer were captain?",capture,0)==0);
 assert(strstr(result,"Hypothetical")&&strstr(result,"Rimmer"));
 used=0;result[0]=0;
 assert(holly_turn(&discussion,"I like Ace Rimmer",capture,0)==0);
 assert(strstr(result,"Ace Rimmer")&&strstr(discussion.topic,"Ace Rimmer"));
 used=0;result[0]=0;
 assert(holly_turn(&discussion,"I think the sound is strange",capture,0)==0);
 assert(strstr(result,"Which Red Dwarf character")&&!strstr(result,"Ace Rimmer"));
 used=0;result[0]=0;
 assert(holly_conversation_only(&discussion,"discussion off",capture,0)==0&&!discussion.discussion_enabled);
 used=0;result[0]=0;
 assert(holly_turn(&discussion,"discussion on",capture,0)==0&&discussion.discussion_enabled);
 struct holly_session hybrid;holly_session_init(&hybrid);
 used=0;result[0]=0;
 assert(holly_turn(&hybrid,"chat on",capture,0)==0&&hybrid.dialogue_model==4);
 used=0;result[0]=0;
 assert(holly_turn(&hybrid,"can we talk",capture,0)==0);
 assert(strstr(result,"experimental")&&strstr(result,"Go ahead")&&hybrid.personality_enabled);
 struct holly_session guest;holly_session_init(&guest);
 used=0;result[0]=0;
 assert(holly_conversation_only(&guest,"chat on",capture,0)==0);
 used=0;result[0]=0;
 assert(holly_conversation_only(&guest,"Who is Lister?",capture,0)==0);
 assert(strstr(result,"stasis")&&strstr(guest.dialogue_previous,"Lister")&&!strstr(guest.dialogue_previous,"https://"));
 puts("Holly command and persona tests passed; dialogue context, session isolation and fact/lesson priority passed");
}
