#!/usr/bin/env python3
"""Validate authored lore JSON and export the original freestanding C table."""
import json
from pathlib import Path
from collections import Counter
R=Path(__file__).resolve().parents[1]
data=json.loads((R/'model/lore/knowledge.json').read_text())
rows=data['topics'];aliases=set();words=Counter()
lines=['/* Generated by tools/export_lore.py; edit model/lore/knowledge.json. */','static const struct lore_entry entries[]={']
for r in rows:
 assert 1<=len(r['pages'])<=3 and 0<len(r['title'])<=48
 assert r['cast_page']==-1 or 0<=r['cast_page']<len(r['pages'])
 for a in r['aliases']:
  assert a and a==a.lower() and len(a)<64 and a not in aliases
  assert all(c.isascii() and (c.isalnum() or c==' ') for c in a)
  aliases.add(a)
 assert len('|'.join(r['aliases']))<256
 for p in r['pages']:
  assert p['text'].isascii() and 0<len(p['text'])<=256
  assert p['source'].startswith('https://reddwarf.co.uk/') and len(p['source'])<180
  words[p['source']]+=len(p['text'].split())
 vals=[json.dumps(r['title']),json.dumps('|'.join(r['aliases'])),str(int(r['guard'])),str(r['cast_page']),str(len(r['pages']))]
 for key in ['text','source']:
  vals.append('{'+','.join(json.dumps(p[key]) for p in r['pages'])+'}')
 lines.append(' {'+','.join(vals)+'},')
lines+=['};','']
# Entire pack remains within each fetched page's 200-word paraphrase budget.
assert all(n<=200 for n in words.values()),[(u,n) for u,n in words.items() if n>200]
(R/'src/lore_data.h').write_text('\n'.join(lines))
print(f'Exported {len(rows)} topics, {sum(len(r["pages"]) for r in rows)} replies; {len(words)} source pages')
