#ifndef HOLLY_EPISODES_H
#define HOLLY_EPISODES_H
/* Catalogue metadata is not a claim that a transcript is installed. */
struct holly_episode { unsigned series; const char *title; };
static const struct holly_episode holly_episodes[]={
{1,"The End"},
{1,"Future Echoes"},
{1,"Balance of Power"},
{1,"Waiting for God"},
{1,"Confidence and Paranoia"},
{1,"Me2"},
{2,"Kryten"},
{2,"Better than Life"},
{2,"Thanks for the Memory"},
{2,"Stasis Leak"},
{2,"Queeg"},
{2,"Parallel Universe"},
{3,"Backwards"},
{3,"Marooned"},
{3,"Polymorph"},
{3,"Body Swap"},
{3,"Timeslides"},
{3,"The Last Day"},
{4,"Camille"},
{4,"DNA"},
{4,"Justice"},
{4,"White Hole"},
{4,"Dimension Jump"},
{4,"Meltdown"},
{5,"Holoship"},
{5,"The Inquisitor"},
{5,"Terrorform"},
{5,"Quarantine"},
{5,"Demons and Angels"},
{5,"Back to Reality"},
{6,"Psirens"},
{6,"Legion"},
{6,"Gunmen of the Apocalypse"},
{6,"Emohawk - Polymorph II"},
{6,"Rimmerworld"},
{6,"Out of Time"},
{7,"Tikka to Ride"},
{7,"Stoke Me a Clipper"},
{7,"Ouroboros"},
{7,"Duct Soup"},
{7,"Blue"},
{7,"Beyond a Joke"},
{7,"Epideme"},
{7,"Nanarchy"},
{8,"Back in the Red, part 1"},
{8,"Back in the Red, part 2"},
{8,"Back in the Red, part 3"},
{8,"Cassandra"},
{8,"Krytie TV"},
{8,"Pete, part 1"},
{8,"Pete, part 2"},
{8,"Only the Good"},
};
#define HOLLY_EPISODE_COUNT (sizeof holly_episodes/sizeof holly_episodes[0])
#endif
