#include "search_disk.h"
#include <string.h>
/* Two copies per topic. Write data sectors, then commit sector; verify all. */
struct entry {uint32_t hash,revision;uint8_t copy,live;};
static struct entry index_bank[256];static struct holly_block_ops io;static uint32_t base;static unsigned ready,count;
static uint32_t get(const uint8_t*p){return (uint32_t)p[0]|(uint32_t)p[1]<<8|(uint32_t)p[2]<<16|(uint32_t)p[3]<<24;}
static void put(uint8_t*p,uint32_t v){for(unsigned i=0;i<4;i++)p[i]=(uint8_t)(v>>(i*8));}
static uint32_t crc(const uint8_t*p,unsigned n){uint32_t x=~0u;for(unsigned i=0;i<n;i++){x^=p[i];for(unsigned b=0;b<8;b++)x=(x>>1)^((0u-(x&1u))&0xedb88320u);}return ~x;}
static uint32_t hash_topic(const char*q){uint32_t h=2166136261u;while(*q)h=(h^(uint8_t)*q++)*16777619u;return h;}
static int read_record(unsigned slot,unsigned copy,uint8_t b[2048]){for(unsigned i=0;i<4;i++)if(io.read(base+2+slot*8+copy*4+i,b+i*512,io.context))return -1;return 0;}
static int has_nul(const uint8_t*p,unsigned n){for(unsigned i=0;i<n;i++)if(!p[i])return 1;return 0;}
static int valid(const uint8_t*b){unsigned t=get(b+20),a=get(b+24),u=get(b+28),live=get(b+16);if(memcmp(b,"HLYWEB26",8)||get(b+8)!=1||!get(b+12)||live>1||crc(b,2044)!=get(b+2044))return 0;if(!live)return t&&t<=192&&!a&&!u&&!has_nul(b+64,t);if(!t||t>192||!a||a>1200||u<9||u>512||t+a+u>1980||get(b+32)<1577836800u||get(b+32)>4102444800u)return 0;if(has_nul(b+64,t+a+u)||memcmp(b+64+t+a,"https://",8))return 0;return 1;}
int holly_search_disk_ready(void){return ready;}
unsigned holly_search_disk_count(void){return count;}
int holly_search_disk_bind(const struct holly_block_ops*ops,uint32_t first,uint32_t sectors){ready=count=0;memset(index_bank,0,sizeof index_bank);if(!ops||!ops->read||!ops->write||sectors<HOLLY_SEARCH_DISK_SECTORS||first>UINT32_MAX-HOLLY_SEARCH_DISK_SECTORS)return -1;io=*ops;base=first;uint8_t header[512],other[512];if(io.read(base,header,io.context)||io.read(base+1,other,io.context))return -1;
 int a=!memcmp(header,"HLYWEBDB",8)&&get(header+8)==1&&get(header+12)==256&&get(header+16)==HOLLY_SEARCH_DISK_SECTORS&&get(header+508)==crc(header,508);int b=!memcmp(other,"HLYWEBDB",8)&&get(other+8)==1&&get(other+12)==256&&get(other+16)==HOLLY_SEARCH_DISK_SECTORS&&get(other+508)==crc(other,508);
 if(!a&&!b){for(unsigned i=0;i<512;i++)if(header[i]||other[i])return -1;uint8_t zero[512]={0};for(unsigned slot=0;slot<256;slot++)for(unsigned copy=0;copy<2;copy++)if(io.write(base+2+slot*8+copy*4,zero,io.context))return -1;memset(header,0,512);memcpy(header,"HLYWEBDB",8);put(header+8,1);put(header+12,256);put(header+16,HOLLY_SEARCH_DISK_SECTORS);put(header+508,crc(header,508));if(io.write(base,header,io.context)||io.read(base,other,io.context)||memcmp(header,other,512))return -1;if(io.write(base+1,header,io.context)||io.read(base+1,other,io.context)||memcmp(header,other,512))return -1;}
 for(unsigned slot=0;slot<256;slot++){uint8_t record[2048];for(unsigned copy=0;copy<2;copy++){if(read_record(slot,copy,record))return -1;if(!valid(record))continue;struct entry*e=&index_bank[slot];uint32_t revision=get(record+12);if(revision<=e->revision)continue;e->revision=revision;e->copy=copy;e->live=get(record+16);unsigned n=get(record+20);char topic[193];memcpy(topic,record+64,n);topic[n]=0;e->hash=hash_topic(topic);}if(index_bank[slot].live)count++;}ready=1;return 0;}
static int locate_any(const char*q,unsigned only_live){uint32_t h=hash_topic(q);unsigned length=(unsigned)strlen(q);for(unsigned i=0;i<256;i++)if(index_bank[i].revision&&index_bank[i].hash==h&&(!only_live||index_bank[i].live)){uint8_t b[2048];if(!read_record(i,index_bank[i].copy,b)&&valid(b)&&get(b+20)==length&&!memcmp(b+64,q,length))return (int)i;}return -1;}
static int locate(const char*q){return locate_any(q,1);}
int holly_search_disk_known(const char*q){if(!ready)return 0;int i=locate_any(q,0);return i<0?0:index_bank[i].live?1:2;}
int holly_search_disk_get(const char*q,char*text,char*source,uint32_t*epoch){if(!ready)return 0;int slot=locate(q);if(slot<0)return 0;uint8_t b[2048];if(read_record((unsigned)slot,index_bank[slot].copy,b)||!valid(b)||!get(b+16)||get(b+12)!=index_bank[slot].revision)return 0;unsigned t=get(b+20),a=get(b+24),u=get(b+28);memcpy(text,b+64+t,a);text[a]=0;memcpy(source,b+64+t+a,u);source[u]=0;*epoch=get(b+32);return 1;}
static int commit(unsigned slot,const char*q,const char*text,const char*source,uint32_t epoch,unsigned live){struct entry*e=&index_bank[slot];if(e->revision==UINT32_MAX)return -1;unsigned copy=e->revision?e->copy^1u:0;uint8_t b[2048]={0},check[2048];memcpy(b,"HLYWEB26",8);put(b+8,1);put(b+12,e->revision+1);put(b+16,live);put(b+32,epoch);unsigned t=(unsigned)strlen(q),a=live?(unsigned)strlen(text):0,u=live?(unsigned)strlen(source):0;put(b+20,t);put(b+24,a);put(b+28,u);memcpy(b+64,q,t);if(live){memcpy(b+64+t,text,a);memcpy(b+64+t+a,source,u);}put(b+2044,crc(b,2044));uint32_t lba=base+2+slot*8+copy*4;for(unsigned i=1;i<4;i++)if(io.write(lba+i,b+i*512,io.context))return -1;if(io.write(lba,b,io.context)||read_record(slot,copy,check)||memcmp(b,check,2048))return -1;
 if(e->live&&!live)count--;
 if(!e->live&&live)count++;
 e->revision++;e->copy=copy;e->live=live;e->hash=hash_topic(q);return 0;}
int holly_search_disk_save(const char*q,const char*text,const char*source,uint32_t epoch){if(!ready||!q||!*q||strlen(q)>192||!text||!*text||strlen(text)>1200||!source||strlen(source)<9||strlen(source)>512||memcmp(source,"https://",8)||epoch<1577836800u||epoch>4102444800u)return -1;int slot=locate(q);if(slot<0)for(unsigned i=0;i<256;i++)if(!index_bank[i].live){slot=(int)i;break;}if(slot<0)return -1;return commit((unsigned)slot,q,text,source,epoch,1);}
int holly_search_disk_forget(const char*q){if(!ready)return -1;int slot=locate(q);if(slot<0)return 1;return commit((unsigned)slot,q,"","",0,0);}
